-- Supabase SQL Schema for Sangjog Vehicle ERP

-- 1. Vehicles Table
CREATE TABLE vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  number_plate TEXT UNIQUE,
  driver_name TEXT,
  image_url TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bank Accounts Table
CREATE TABLE bank_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_name TEXT NOT NULL,
  bank_name TEXT,
  balance REAL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Transactions Table
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT CHECK(type IN ('income', 'expense')) NOT NULL,
  category TEXT NOT NULL,
  amount REAL NOT NULL,
  date TIMESTAMPTZ DEFAULT NOW(),
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE SET NULL,
  bank_account_id BIGINT REFERENCES bank_accounts(id) ON DELETE SET NULL,
  description TEXT,
  odometer_reading REAL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Settings Table
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Monthly Opening Balances Table
CREATE TABLE monthly_opening_balances (
  month TEXT PRIMARY KEY, -- Format: YYYY-MM
  amount REAL DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Driver Advances Table
CREATE TABLE driver_advances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
  amount REAL NOT NULL,
  date TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'pending', -- 'pending', 'settled'
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Categories Table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT CHECK(type IN ('income', 'expense')) NOT NULL,
  UNIQUE(name, type),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed default categories
INSERT INTO categories (name, type) VALUES 
('ভাড়া (Rent)', 'income'),
('তেল খরচ (Fuel)', 'expense'),
('ড্রাইভার বেতন (Driver Salary)', 'expense'),
('গাড়ি মেরামত (Maintenance)', 'expense'),
('টোল (Toll)', 'expense'),
('পুলিশ খরচ (Police Expense)', 'expense'),
('অন্যান্য (Others)', 'income'),
('অন্যান্য (Others)', 'expense')
ON CONFLICT DO NOTHING;

INSERT INTO settings (key, value) VALUES ('opening_balance', '0')
ON CONFLICT DO NOTHING;
